## Matrix Calculator Using Numpy

In [1]:
import numpy as np

In [2]:
def add_mtrx(matA,matB):
    return np.add(matA,matB)

In [3]:
def mul_mtrx(matA,matB):
    return np.dot(matA,matB)

In [4]:
def det_mtrx(matA):
    return np.linalg.det(matA)

In [5]:
def trans_mtrx(matA):
    return matA.T

In [6]:
def inverse_mtrx(matA):
    if det_mtrx(matA)==0:
        return "Inverse is not possible"
    return np.linalg.inv(matA)

In [7]:
matA=np.array([[1,2],[3,4]])
matB=np.array([[5,6],[7,8]])

print(matA)
print("---------")
print(matB)

print("Addition of two matrices:",add_mtrx(matA,matB))



[[1 2]
 [3 4]]
---------
[[5 6]
 [7 8]]
Addition of two matrices: [[ 6  8]
 [10 12]]


In [8]:
print(matA)
print("---------")
print(matB)

print("multiplication of two matrices:",mul_mtrx(matA,matB))

[[1 2]
 [3 4]]
---------
[[5 6]
 [7 8]]
multiplication of two matrices: [[19 22]
 [43 50]]


In [9]:
print(matA)
print("---------")
print(matB)

print("Determinant of  matrix A:",det_mtrx(matA))
print("Determinant of  matrix B:",det_mtrx(matB))

[[1 2]
 [3 4]]
---------
[[5 6]
 [7 8]]
Determinant of  matrix A: -2.0000000000000004
Determinant of  matrix B: -2.000000000000005


In [10]:
print(matA)
print("---------")
print(matB)

print("transpose of matrix A:",trans_mtrx(matA))
print("transpose of matrix B:",trans_mtrx(matB))

[[1 2]
 [3 4]]
---------
[[5 6]
 [7 8]]
transpose of matrix A: [[1 3]
 [2 4]]
transpose of matrix B: [[5 7]
 [6 8]]


In [11]:
print(matA)
print("---------")
print(matB)

print("Inverse of matrix A:",inverse_mtrx(matA))
print("Inverse of matrix B:",inverse_mtrx(matB))


[[1 2]
 [3 4]]
---------
[[5 6]
 [7 8]]
nverse of matrix A: [[-2.   1. ]
 [ 1.5 -0.5]]
nverse of matrix B: [[-4.   3. ]
 [ 3.5 -2.5]]
